version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin} # 数据库用户名
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456} # 数据库密码
      POSTGRES_DB: ${POSTGRES_DB:-main_db} # 默认数据库名
